include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    unnecessary_null_comparison: warning

  exclude:
    - build/**
    - .dart_tool/**

linter:
  rules:
    # Import rules
    prefer_relative_imports: true
    always_use_package_imports: false

    # Style rules
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    unnecessary_this: true

    # Code quality
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true