// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4akvUU8XZigRjQDZcNipHvwqdikSw5OM',
    appId: '1:254371130671:web:93b344fb48f833882d85da',
    messagingSenderId: '254371130671',
    projectId: 'planmate-depi',
    authDomain: 'planmate-depi.firebaseapp.com',
    storageBucket: 'planmate-depi.firebasestorage.app',
    measurementId: 'G-Y1MFL5ZP3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzGTeeWoAZcAtIp1pusojdqlHNma9TJkY',
    appId: '1:254371130671:android:5fad89f5672b6c972d85da',
    messagingSenderId: '254371130671',
    projectId: 'planmate-depi',
    storageBucket: 'planmate-depi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjJmuJbTziTfQ3JaQfPP0TvrXnwLpS-6w',
    appId: '1:254371130671:ios:06e613f7eb989a1d2d85da',
    messagingSenderId: '254371130671',
    projectId: 'planmate-depi',
    storageBucket: 'planmate-depi.firebasestorage.app',
    iosClientId: '254371130671-l7ihsblq9vk5hg31qm7rlp9gom2oeplj.apps.googleusercontent.com',
    iosBundleId: 'com.example.planmateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjJmuJbTziTfQ3JaQfPP0TvrXnwLpS-6w',
    appId: '1:254371130671:ios:06e613f7eb989a1d2d85da',
    messagingSenderId: '254371130671',
    projectId: 'planmate-depi',
    storageBucket: 'planmate-depi.firebasestorage.app',
    iosClientId: '254371130671-l7ihsblq9vk5hg31qm7rlp9gom2oeplj.apps.googleusercontent.com',
    iosBundleId: 'com.example.planmateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4akvUU8XZigRjQDZcNipHvwqdikSw5OM',
    appId: '1:254371130671:web:b49b447952a960602d85da',
    messagingSenderId: '254371130671',
    projectId: 'planmate-depi',
    authDomain: 'planmate-depi.firebaseapp.com',
    storageBucket: 'planmate-depi.firebasestorage.app',
    measurementId: 'G-SET8L69V6W',
  );

}